version: '3.8'
services:
  postgres_db_stock_management:
    container_name: postgres_db_stock_management
    image: postgres:14-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_management
    ports:
      - "5432:5432"
    volumes:
      - volume_postgres_db_stock_management:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "pg_isready -U postgres | grep 'accepting connections' || exit 1"
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - stock-management-network-postgres
  redis:
    container_name: redis
    hostname: redis
    image: redis
    volumes:
      - "../data/redis:/var/lib/redis/data"
    networks:
      - stock-management-network-redis
    expose:
      - 6379
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          memory: 1G
          cpus: "1.0"

  eureka-server:
    #container_name: eureka-server
    hostname: eureka-server
    image: pblgllgs/eureka-server-tk:1.0.0
    networks:
      - stock-management-network-backend
    expose:
      - 8761
    depends_on:
      config-server:
        condition: service_started
    ports:
      - 8761:8761
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      - "SPRING_PROFILES_ACTIVE=stage"
    entrypoint: [ "java","-jar","app.jar" ]

  product-service:
    #container_name: product-service
    hostname: product-service
    image: pblgllgs/product-service-tk:1.0.0
    depends_on:
      postgres_db_stock_management:
        condition: service_healthy
      zuul-edge-server:
        condition: service_started
    networks:
      - stock-management-network-backend
      - stock-management-network-postgres
    expose:
      - 9788
    ports:
      - 9788:9788
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      - "SPRING_PROFILES_ACTIVE=stage"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=password"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db_stock_management:5432/stock_management"
    entrypoint: [ "java","-jar","app.jar" ]

  zuul-edge-server:
    hostname: zuul-edge-server
    image: pblgllgs/api-gateway-tk:1.0.0
    networks:
      - stock-management-network-backend
    depends_on:
      config-server:
        condition: service_started
    expose:
      - 8762
    ports:
      - 8762:8762
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      - "SPRING_PROFILES_ACTIVE=stage"
    entrypoint: [ "java","-jar","app.jar" ]

  product-cache-service:
    hostname: product-cache-service
    image: pblgllgs/product-cache-service-tk:1.0.0
    networks:
      - stock-management-network-backend
      - stock-management-network-redis
    depends_on:
      redis:
        condition: service_healthy
      zuul-edge-server:
        condition: service_started
    expose:
      - 9791
    ports:
      - 9791:9791
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      - "SPRING_PROFILES_ACTIVE=stage"
    entrypoint: [ "java","-jar","app.jar" ]

  config-server:
    hostname: config-server
    image: pblgllgs/config-server-tk:1.0.0
    networks:
      - stock-management-network-backend
    expose:
      - 9791
    ports:
      - 8888:8888
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      - "SPRING_PROFILES_ACTIVE=stage"
    entrypoint: [ "java","-jar","app.jar" ]

networks:
  stock-management-network-backend:
  stock-management-network-postgres:
  stock-management-network-redis:
volumes:
  volume_postgres_db_stock_management:
    external: false