spring:
  application:
    name: config-server
  profiles:
    active: localhost
info:
  component: config Server

---

spring:
  profiles: localhost
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rabiayurdakul/stockmanagement-configs.git
logging:
  level:
    root: debug
server:
  port: 8888

---

spring:
  profiles: stage
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rabiayurdakul/stockmanagement-configs.git
logging:
  level:
    root: debug
server:
  port: 8888